version: '2.3'

services:
  face_recognition:
    image: face_recognition
    container_name: face_recognition
    working_dir: /face_recognition/app
    build:
      context: .
      #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
      # dockerfile: Dockerfile.gpu
    # command: python3 -u face_location.py
    # command: python3 -u encode_faces.py -i face_images -e encodings.pickle
    command: python3 -u cluster_faces.py -e encodings.pickle
    volumes:
      - ./:/face_recognition
    #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
    # runtime: nvidia
